In [ ]:
# import library of functions
from numpy import exp, array, random, dot

In [ ]:
# the neural network class
class NeuralNetwork():
    def __init__(self):
        # seed the random number generator so the same
        # numbers are generated every time
        random.seed(1)
        
        # initialize the weights as a 3 x 1 matrix
        self.synaptic_weights = 2 * random.random((6, 4)) - 1 # value range from -1 to 1
        
    # the activation function
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))
    
    # the sigmoid derivative
    # shows how much to change the weights by
    def __sigmoid_derivative(self, x):
        return x * (1 - x)
    
    # train the neural network by changing the weights each time
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iterations in range(number_of_training_iterations):
            # pass the training set into our neural network
            output = self.think(training_set_inputs)
            
            # calculate the error
            error = training_set_outputs - output
            
            # multply the error by the input and by the gradient of the sigmoid
            # the less confident weights are adjusted more
            # this means inputs, which are 0, do not adjust the weights
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))
            
            # adjust the weights with the adjustment
            self.synaptic_weights += adjustment
            
    def think(self, inputs):
        return self.__sigmoid(dot(inputs, self.synaptic_weights))
    




In [8]:
# declare the possible inputs and outputs
possible_inputs = [[1, 0, 0, 1, 1, 0], [1, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0], [1, 1, 1, 1, 1, 1]]
possible_outputs = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]

if __name__ == "__main__":
    
    # initialize the neural network
    neural_network = NeuralNetwork()
    
    print ("Random starting synaptic weights: ")
    print (neural_network.synaptic_weights)
    
    # the training set has 3 inputs and 1 output
    training_set_inputs = array(possible_inputs)
    training_set_outputs = array(possible_outputs).T
    
    # Train the neural network with our set
    # Do it 10,100 times
    neural_network.train(training_set_inputs, training_set_outputs, 100000)
    
    print ("New synaptic weights after training: ")
    print (neural_network.synaptic_weights)
    
    # Test the neural network with a new situation
    print ("Considering new situation [0.75, 0.1, 0.1, .86, .93, .14] -> ")
    print (neural_network.think(array([0.75, 0.1, 0.1, .86, .93, .14])))
    
    # This fails on a one-layer neural network...
    print ("Considering new situation [0.854, 0.761, 0.000, 0.736, 0.798, 0.762]] -> ")
    print (neural_network.think(array([0.854, 0.761, 0.000, 0.736, 0.798, 0.762])))
 

Random starting synaptic weights: 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]
 [-0.5910955   0.75623487 -0.94522481  0.34093502]
 [-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]]
New synaptic weights after training: 
[[-5.62018195  5.75332638 -6.38230839 -5.82243211]
 [-2.70415747 -1.27114702 -1.9319406   6.71317261]
 [-8.41250066 -1.5099004   3.92363657 -1.55811979]
 [ 2.38537993 -6.17911571  2.25038249 -4.3576786 ]
 [ 9.0194514  -5.68626126 -2.91332738  3.6481993 ]
 [-1.39618011  0.48069894 -1.67761266  7.40669638]]
Considering new situation [0.75, 0.1, 0.1, .86, .93, .14] -> 
[ 0.99273394  0.00150407  0.00369714  0.04034294]
Considering new situation [0.854, 0.761, 0.000, 0.736, 0.798, 0.762]] -> 
[  7.37259559e-01   8.38263333e-03   1.40861471e-04   9.95865647e-01]
