In [23]:
# import library of functions
from numpy import exp, array, random, dot, mean, abs

In [24]:
input_data = array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
output_labels = array([[0],
            [1],
            [1],
            [0]])

print(input_labels)
print(output_labels)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [25]:
# the activation function
def __sigmoid(x):
        return 1 / (1 + exp(-x))
    
# the sigmoid derivative
# shows how much to change the weights by
def __sigmoid_derivative(x):
        return x * (1 - x)


In [26]:
# the weights
synaptic_weight_0 = 2 * random.random((3, 4)) - 1
synaptic_weight_1 = 2 * random.random((4, 1)) - 1

print(synaptic_weight_0)
print(synaptic_weight_1)

[[-0.90009308  0.07179281  0.32758929  0.02977822]
 [ 0.88918951  0.17311008  0.80680383 -0.72505059]
 [-0.72144731  0.61478258 -0.20464633 -0.66929161]]
[[ 0.85501716]
 [-0.30446828]
 [ 0.50162421]
 [ 0.45199597]]


In [27]:
# iterate over the data 
iterations = 60000
for j in range(iterations):

	# Forward propagate through layers 0, 1, and 2
    layer0 = input_data
    layer1 = __sigmoid(dot(layer0, synaptic_weight_0))
    layer2 = __sigmoid(dot(layer1, synaptic_weight_1))

    #calculate error for layer 2
    layer2_error = output_labels - layer2
    
    if (j% 10000) == 0:
        print ("Error: " + str(mean(abs(layer2_error))))
        
    #Use it to compute the gradient
    layer2_adjustment = layer2_error * __sigmoid_derivative(layer2)

    #calculate error for layer 1
    layer1_error = layer2_adjustment.dot(synaptic_weight_1.T)
    
    #Use it to compute its gradient
    layer1_adjustment = layer1_error * __sigmoid_derivative(layer1)
    
    #update the weights using the gradients
    synaptic_weight_1 += layer1.T.dot(layer2_adjustment)
    synaptic_weight_0 += layer0.T.dot(layer1_adjustment)

Error: 0.49721742951
Error: 0.00958553541507
Error: 0.00661810936946
Error: 0.00534673664535
Error: 0.00460078940831
Error: 0.00409675042082


In [28]:
# test the neural network
print(__sigmoid(dot(array([0, 1, 1]), synaptic_weight_0)))

[  9.60692875e-01   9.99590016e-01   7.88985874e-01   3.82593416e-04]
